server {
    listen 80;

    server_name localhost;

    # Servir arquivos estáticos
    location /static/ {
        root /usr/share/nginx/html;
    }

    location /templates/ {
        root /usr/share/nginx/html;
    }

    # Proxy para o backend Flask
    location / {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
