events {
    worker_connections 1024;
}

http {
    upstream flask_backend {
        server backend:5000;
    }

    server {
        listen 80;

        # Frontend estático
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /static {
            root /usr/share/nginx/html;
        }

        # Proxy para API Flask
        location /pontos {
            proxy_pass http://flask_backend;
        }

        location /detalhes {
            proxy_pass http://flask_backend;
        }
    }
}
