events {
    worker_connections 1024;
}

http {
    upstream flask_backend {
        server backend:5000;
    }

    # compressão Gzip
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        application/javascript
        application/json
        application/xml
        text/javascript
        image/svg+xml;  # tipos de arquivos a comprimir
    gzip_vary on;   # adiciona header Vary: Accept-Encoding

    server {
        listen 80;

        # Frontend estático
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Cache para arquivos estáticos
        location /static {
            root /usr/share/nginx/html;
            expires 7d;                # mantém no cache por 7 dias
            add_header Cache-Control "public";
        }

        # Proxy para API Flask
        location /pontos {
            proxy_pass http://flask_backend;
        }

        location /detalhes {
            proxy_pass http://flask_backend;
        }
    }
}
