name: CI - Flask Redis App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest python-dotenv redis

    - name: Rodar lint com flake8
      run: flake8 .

    - name: Rodar testes com pytest
      run: pytest || echo "Sem testes por enquanto"
